# Generated by Django 5.0.4 on 2024-04-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bms", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
