# Generated by Django 5.0.4 on 2024-04-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bms", "0002_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="stadium",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
