# Generated by Django 5.0.4 on 2024-04-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bms", "0004_alter_stadium_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stadium",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
